# Generated by Django 2.2 on 2020-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200601_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catagory',
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ManyToManyField(to='product.Catagory'),
        ),
    ]
