# Generated by Django 2.2 on 2020-06-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200601_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catagory',
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Catagory'),
        ),
    ]
